### ISSUE TITLE
"View Image in Browser" option triggers download instead

### ISSUE THREAD

**Issue by ellenemerson** [DigitalSlideArchive/digital_slide_archive#108]
Hello again,

Now that I was able to get the docker containers up and running and log into HistomicsUI, I'm running into an issue actually viewing images in the UI.  I don't see an image viewer, and when I click on the image name or the "View Image in Browser" option, a download is triggered instead of a viewer opening.  

I'm importing existing images through a filesystem assetstore.  Images are untiled BigTIFFs, though I also tried converting to regular tiff and had the same problem.  

Is there a required format I am missing? 

Thanks!

**Comment by manthey** [comment]
The "View Image In Browser" button is a Girder feature that, if your browser supports viewing an image with the current mime-type, will view it.  Most browsers don't view TIFF directly.

In the default DSA installation, the large_image library is used to view tiled image source (TIFF, svs, np2, etc.).  Non-tiled sources aren't viewed by the large_image library in the default configuration.  There is a button 
![image](https://user-images.githubusercontent.com/8781639/80403096-042c4d80-888d-11ea-9c7b-9f2c1b672842.png) on the item page that will convert the file to a large-image compatible format, if possible.  If the image is small (the threshold is configurable), it will be viewed via the PIL tile source.  If it is large, it is converted by vips to a pyramidal tiled tiff.

**Comment by ellenemerson** [comment]
Excellent - thank you! 

One more question about the file system assetstore: when new data is added to that filesystem, is there a way to automatically populate that data in the UI? or would manual import of existing data be required each time?

**Comment by manthey** [comment]
There isn't anything that checks for new files -- you have to manually import data after file system changes.  We've discussed adding such a feature, but it is actually complex: if a file has moved, do we move it? If a user has moved a file in the GirderUI do we put it back? If a directory is missing, do we remove files, or, should we maintain references to them since they may come back (it could be a mount on the user's system that is temporarily unavailable)?

**Comment by manthey** [comment]
Closing this.  We've discussed adding better tools for reimporting from a directory elsewhere.
