### ISSUE TITLE
Permission denied when adding slicer plugins

### ISSUE THREAD

**Issue by alex-posea** [DigitalSlideArchive/digital_slide_archive#142]
Getting this error

`Started to Load Docker images`
`Failed to create the Docker Client`
`Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))`
`Error with job `
  `Could not create the docker client (image name: None )`

When trying to add slicer plugins after deploying with docker-compose (tried it on both Ubuntu and WSL2)

**Comment by manthey** [comment]
Did you start docker-compose with an appropriate user (e.g., `DSA_USER=$(id -u):$(id -g) docker-compose up`), and is that user a member of the docker group?  Is the docker installation standard, or are some permissions restricted?

**Comment by manthey** [comment]
Closing without further information.
