### ISSUE TITLE
best way to connect to localhost in google cloud

### ISSUE THREAD

**Issue by Gibbsdavidl** [DigitalSlideArchive/digital_slide_archive#145]
Hi there,

I have the docker-compose method seemingly working, running on a google vm... should be running by default on localhost:8080.  Could you recommend a good way to connect to it?  I see methods like using ngrok to expose the localhost, or maybe a firewall rule?  Thanks for any thoughts on this.

-dave

**Comment by Leengit** [comment]
I'm not exactly sure of your set up, but guessing a little:

1. to expose 8080 from the docker to its local host you can use `-p 8080:8080` as an option for your `docker run` command.
2. to connect from your desktop to the google vm, a `LocalForward 8080 localhost:8080` option for an SSH connection would do.

**Comment by Gibbsdavidl** [comment]
Ah ha, thanks for the response.  Yes, using very default ubuntu VMs.  Docker often trips me up!

I was starting it with, DSA_USER=$(id -u):$(id -g) docker-compose up
     
does the -p 8080:8080  work in that case too?

I'll give it a go, thanks!
