### ISSUE TITLE
Installation/deployment via singularity

### ISSUE THREAD

**Issue by sarthakpati** [DigitalSlideArchive/digital_slide_archive#167]
Hi,

Would it be possible for you to update the [installation documentation](https://github.com/DigitalSlideArchive/digital_slide_archive/blob/master/ansible/README.rst) to add notes about how to use [singularity](https://singularityhub.github.io/)?

Ideally, it would be great to have an alternative to [`deploy_docker.py`](https://github.com/DigitalSlideArchive/digital_slide_archive/blob/master/ansible/deploy_docker.py) to have something like `deploy_singularity.py`. 😄

Cheers,
Sarthak

**Comment by manthey** [comment]
See an initial rough example: https://github.com/DigitalSlideArchive/digital_slide_archive/tree/singularity-minimal/devops/singularity-minimal.  I'll make that a PR and merge it as a demo example.
