### ISSUE TITLE
CI is stalled

### ISSUE THREAD

**Issue by theNewFlesh** [DigitalSlideArchive/digital_slide_archive#177]
I am waiting on CI to run on a [PR](https://github.com/DigitalSlideArchive/digital_slide_archive/pull/176)   I submitted several hours ago. Does CI normally take this long?

**Comment by manthey** [comment]
CI builds weren't enabled for forked pull requests.  They now are.  You probably have to bump that branch for CI to notice.

**Comment by theNewFlesh** [comment]
Can I get a review on that PR?
https://github.com/DigitalSlideArchive/digital_slide_archive/pull/176
