### ISSUE TITLE
Asssetstore migration

### ISSUE THREAD

**Issue by ds2268** [DigitalSlideArchive/digital_slide_archive#188]
I have an existing DSA employment (.dsa/) on HDD and would like to move deployment to another filesystem location on SSD. I have copied .dsa/ folder alltogether to the new location and re-deployed DSA with new --asssetstore value, but it didn't work -collections with samples were empty. I suspect that that are some absolute paths to the actual data in MongoDB which prevent from directly moving the images/assetstore around? How can I achieve that?

**Comment by manthey** [comment]
Assuming you are using the `deploy_docker.py` script, there are three different things mounted to the ~/.dsa directory -- assetstore, db, and logs.  If you moved the entire ~/.dsa directory, You need to override all three: `--assetstore=<new dir>/assetstore --db=<new dir>/db --logs=<new dir>/logs`.  There shouldn't be anything inside the database or docker images with the external paths; they are just mounted as docker volumes.

**Comment by ds2268** [comment]
Thanks! Tried again and the issue is solved. Maybe I have used relative paths before. Thanks!
