### ISSUE TITLE
Wiki: VIPS and OpenSlide Installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by ohsofoxy273** [DigitalSlideArchive/digital_slide_archive#2]
After the recommended installation on the wiki page I needed to run: sudo ldconfig

**Comment by dgutman** [comment]
Yes thanks... We need to add that to the wiki.   I had installed another
random package during the full install which had ran ldconfig for me... And
it took me a while to realize why it didn't work on a new build...

I'll update the wiki ASAP..

**Comment by brianhelba** [comment]
https://github.com/DigitalSlideArchive/ansible-role-vips now does this automatically.
