### ISSUE TITLE
Create a sample script for Girder item manipulation

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/digital_slide_archive#20]
To start, this can be a Python script utilizing the [Girder Python Client](https://girder.readthedocs.io/en/latest/python-client.html). Eventually, we may want to put it into an iPython Notebook, but that can be done by users.

For the first iteration, the script should:
1. Connect to https://girder.neuro.emory.edu/ , and authenticate. User credentials (particularly password) can be read from standard input at runtime, or passed as command line arguments.
2. Create a new subfolder in the "DG TCGA" collection called  "GBM"
3. Get a list of all large_image items that currently live in "DG TCGA". If items are not already marked as large_image, find all items with SVS files, and mark them as large_image first.
4. Within the recently created GBM folder, create subfolders "PATIENT1", "PATIENT2", and "PATIENT3"
4. Move one of the large_image items to the recently created folder PATIENT1
5. Set the following metadata on the "PATIENT1" folder:
`"PatientAge":  22`
`"PatientDeceased": True`
6. Set the following metadata on the large_image item:
`"SlideSource": "FromTCGA"`
`"SlideType": "DX"`
7. Look for empty folders and delete them, as large_image items that are moved into the "PATIENT*" hierarchy will leave empty folders behind.
8. Find and delete any items containing a "README.TXT" file.

**Comment by salamb** [comment]
@brianhelba 
Some clarifications needed
# 7 Within the collection delete folders that are completely empty or just when there are no more large images left(within the actual archive there are multiple txt files)
# 8  Within the collection, delete items named README.txt, or delete any item that contains a file named README.txt

**Comment by brianhelba** [comment]
@salamb On 7, let's delete all folders that are completely empty.

On 8, delete any items containing the file "README.txt". Note, as a practical matter, I expect there's only 1 file per item in this case, but we shouldn't rely on that fact.

**Comment by salamb** [comment]
@brianhelba 
Is their a way in the girder client to get /resource/search under a specific collection or directory? I can only get it to search the entire database and i don't see such options in the interactive api. If not I will use a recursive search.

**Comment by brianhelba** [comment]
@salamb I think the recursive search is better anyway, since we're trying to write a clear example on how to browse and manipulate a Girder instance, as opposed to doing things in a more efficient but obscure way.

**Comment by salamb** [comment]
@brianhelba 
If you have a series of nested folders with a single uploaded image in the leaf/last child folder. parent folders of the child folder have a size of 0. I found the issue #454 on girders repo. I was originally deleting all folders of size 0 which included GBM. Do you want me to delete all folders with just zero contents or recursively determine if the size is zero in the case sub folders actually have zero size .

**Comment by brianhelba** [comment]
@salamb Recursively check the size. Only folders which are truly empty should be deleted.

**Comment by manthey** [comment]
Closing due to age.
