### ISSUE TITLE
Problem when I use devops scripts.

### ISSUE THREAD

**Issue by Shao-YJ** [DigitalSlideArchive/digital_slide_archive#212]
I want mount local source folder in the container,but when I ues order "devops/deploy.sh start --build",it occured a error and failed.

The build log is this:
Building worker
Step 1/23 : FROM ubuntu:20.04

---> Using cache
---> 3d4874a4bcb4
Step 18/23 : RUN ansible-playbook -i inventory/local docker_ansible.yml --extra-vars="docker=girder_worker" &&     sudo rm -rf /var/lib/apt/lists/* /tmp/*                 /home/ubuntu/.cache                 /home/ubuntu/.ansible*                 /home/ubuntu/.wget-hsts                 /root/.cache/pip &&     sudo find / -xdev -name '*.py[oc]' -type f -exec rm {} \+ &&     sudo find / -xdev -name __pycache__ -type d -exec rm -r {} \+

---> Running in fbb09921364c
PLAY [local] *******************************************************************
TASK [Gathering Facts] *********************************************************
ok: [localhost]
TASK [common : Ensure the girder group exists] *********************************
ok: [localhost]
TASK [common : Ensure the girder user exists] **********************************
changed: [localhost]
TASK [common : Give ownership of root dir to appropriate user] *****************
changed: [localhost]
TASK [common : Install curl] ***************************************************
ok: [localhost]
TASK [common : Install aptitude] ***********************************************
changed: [localhost]
TASK [common : Upgrade system packages] ****************************************
changed: [localhost]
TASK [common : Install pycurl and apt-transport-https package in order to use the apt_repository module and install from https] ***
changed: [localhost]
TASK [common : Install packages needed for girder plugins] *********************
changed: [localhost]
TASK [common : Create a docker group] ******************************************
changed: [localhost]
TASK [common : Join the docker group] ******************************************
changed: [localhost]
TASK [common : Set /opt to public] *********************************************
changed: [localhost]
TASK [common : Add .vimrc to make developers happy] ****************************
changed: [localhost]
TASK [common : Fetch python3-distutils] ****************************************
ok: [localhost]
TASK [worker : Install gpg dependencies] ***************************************
skipping: [localhost]
TASK [worker : Fetch GPG key for docker package] *******************************
changed: [localhost]
TASK [worker : Add docker PPA] *************************************************
skipping: [localhost]
TASK [worker : Install worker dependencies] ************************************
skipping: [localhost]
TASK [worker : Start docker daemon] ********************************************
skipping: [localhost]
TASK [worker : Clone girder_worker] ********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote git://github.com/girder/girder_worker.git -h refs/heads/master", "msg": "fatal: remote error: \n  The unauthenticated git protocol on port 9418 is no longer supported.\nPlease see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.", "rc": 128, "stderr": "fatal: remote error: \n  The unauthenticated git protocol on port 9418 is no longer supported.\nPlease see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.\n", "stderr_lines": ["fatal: remote error: ", "  The unauthenticated git protocol on port 9418 is no longer supported.", "Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information."], "stdout": "", "stdout_lines": []}
PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=11   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

Removing intermediate container fbb09921364c

Error building worker

Any suggestions? Thanks in advance!

**Comment by manthey** [comment]
github changed some configuration settings.  We addressed this in https://github.com/DigitalSlideArchive/digital_slide_archive/pull/200.  Please pull the latest version and try again.
