### ISSUE TITLE
Custom Search Endpoint based on metadata

### ISSUE THREAD

**Issue by dgutman** [DigitalSlideArchive/digital_slide_archive#29]
We need to have some tutorials/examples on how I can create various custom endpoints that search and retrieve folders or items based on CUSTOM metadata..

So for example, for Collection X...    I have FOLDER level metadata, and I want to get a list of all folders that have the key  patientID: "11111"

Another example would be finding all folders that have say patientID:"11111" and stainType: "H&E"

I need to be able to build/update these endpoints in the Girder interface.

Also I want to have another mode that returns the ITEMS that match a specific query.. so in this case I may want to return all slides that match patientID:"11111" and stainType: "NISSL"

These should be performant, so that as it sees a new metadata field, it ensures they are indexed, or we have a separate endpoint where I can add indexes (or compound indexes) ...

@jbeezley  @manthey  @zachmullen   Zach said this should be fairly to prototype..

**Comment by dgutman** [comment]
I think as part of this, I may also want a separate endpoint to return all of the UNIQUE values associated with a specific metadata key... for example I can imagine wanting to know a list of ALL available stains in a colleciton, as this would then serve as a dropdown box/selection tool for the UI... better yet would be to return both the  unique items, and the COUNT associated with each item..

**Comment by manthey** [comment]
Much of this was done with a custom query endpoint (in HistomicsUI) and returning counts in the headers in Girder.  I'll close this issue and we can open new issues with specific further changes.
