### ISSUE TITLE
Modify the style of the main interface.

### ISSUE THREAD

**Issue by XmySz** [DigitalSlideArchive/digital_slide_archive#330]
![image](https://github.com/DigitalSlideArchive/digital_slide_archive/assets/50696554/450ecd90-807d-4ebf-b598-9c7164f774f8)
Hello, thank you for this great job. I would like to know how to modify the style on the main page (as shown by the red arrow in the picture), or add additional modules (as shown by the red rectangle in the picture). Thank you!

**Comment by XmySz** [comment]
Thank u Very!!!

**Comment by XmySz** [comment]
Thank you very much for your assistance. However, I have another query. I intend to modify the names of the components shown in the image, possibly by simply localizing them into Chinese. I have been unable to find relevant options within the plugin. Could you please advise on how to proceed with these modifications? I sincerely appreciate your response.😘😘😘😘






![image](https://github.com/DigitalSlideArchive/digital_slide_archive/assets/50696554/98e844f1-5b73-4b4f-9140-a4f844383758)

**Comment by manthey** [comment]
You would need to either modify the existing code or write a plugin that would substitute the text in the existing interface.  We haven't (yet) done much work for multi-language translation files.
