### ISSUE TITLE
DSA heatmaps

### ISSUE THREAD

**Issue by rogertrullo** [DigitalSlideArchive/digital_slide_archive#372]
Hi, I am deploying using the [devops folder](https://github.com/DigitalSlideArchive/digital_slide_archive/tree/master/devops/dsa).
I am trying to visualize heatmaps; which I am manually uploading using the json annotations as shown [here](https://github.com/girder/large_image/blob/master/girder_annotation/docs/annotations.rst). It seems only polygons are visible. Is this expected? if so, what is the correct way to add overlays shuch os other images, heatmaps, etc?
Thanks!

**Comment by manthey** [comment]
Does your annotation that you are uploading conform to the schema?  A minimum heatmap might look like:
```
{
  "name": "A name for this annotation",
  "elements": [
    {
      "type": "heatmap",
      "points": [
        [512, 512, 0, 0],
        [1024, 512, 0, 0.5],
        [1536, 512, 0, 0.25],
        .... 
      ],
  "radius": 1000, 
  "scaleWithZoom" true
}
```
Points are in the form of x, y, z, value.  The radius and scaleWithZoom are optional but if unset might mean that the heatmap doesn't show up well at some scales.  A useful radius is roughly the area of significance of your points.

If what you upload doesn't conform to the schema (such as you didn't add it as an element of an annotation), you'll see a message in the logs about that.

**Comment by rogertrullo** [comment]
oh it was just that the radius was too small, so I was not seeing it, thanks!. It works fine we can close this. Btw, those logs, where can we see them?

**Comment by manthey** [comment]
From the swagger interface they are at GET system/logs (the info log contains everything, the error log only contains a limit set).  Using the default docker compose, they will also be on your local file system at devops/dsa/logs/info.log
