### ISSUE TITLE
Question about pathological report

### ISSUE THREAD

**Issue by YZYwoazzzzz** [DigitalSlideArchive/digital_slide_archive#40]
Hi, developers
Pathological report needs log in. How could I get this account?
Best regards,
Yzy.

**Comment by manthey** [comment]
If you installed this using the deployment scripts and haven't changed it, there is a default admin account (username: admin, password: password).  Otherwise, ask whomever set up the deployment.

**Comment by manthey** [comment]
Closing.  Please reopen if there is a remaining issue.
