### ISSUE TITLE
Links in secondary webite pages don't work right

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/digital_slide_archive#94]
The links we just added to secondary website pages aren't resolving properly when built by jekyll.

**Comment by manthey** [comment]
@faiza-a @jtomeck Can either of you take at look at this relatively quickly?

**Comment by faiza-a** [comment]
@manthey we are in meeting right now. @jtomeck will have a look at this right after meeting.

**Comment by manthey** [comment]
Resolved by #95.
